// Trivia question bank.
// Each question: { theme, category, difficulty, q, choices: [...], answer: <index>, fact? }
//   theme      — top-level pack the player selects (e.g. "Marvel")
//   category   — short on-screen sub-tag
//   difficulty — "easy" | "medium" | "hard"
//   answer     — 0-based index into `choices`
// Answers have been checked for accuracy. Keep questions unambiguous.

const QUESTIONS = [
  // =====================================================================
  // ============== THEME: MILLENNIAL NOSTALGIA ==========================
  // =====================================================================

  // ---------- TV ----------
  {
    theme: "Millennial Nostalgia",
    category: "TV",
    difficulty: "hard",
    q: "In Friends, what is the name of Ross and Monica's family dog that supposedly went to live on a farm?",
    choices: ["Chi-Chi", "Marcel", "Clunkers", "LaPooh"],
    answer: 2,
    fact: "Clunkers — though fans also remember Marcel the monkey, who was Ross's pet, not a dog.",
  },
  {
    theme: "Millennial Nostalgia",
    category: "TV",
    difficulty: "easy",
    q: "What was the name of the coffee shop where the Friends gang always hung out?",
    choices: ["Central Perk", "The Grind", "Café Nervosa", "Luke's Diner"],
    answer: 0,
  },
  {
    theme: "Millennial Nostalgia",
    category: "TV",
    difficulty: "easy",
    q: "On The Fresh Prince of Bel-Air, what city did Will move FROM?",
    choices: ["Compton", "Philadelphia", "Detroit", "Oakland"],
    answer: 1,
    fact: "\"In West Philadelphia born and raised...\"",
  },
  {
    theme: "Millennial Nostalgia",
    category: "TV",
    difficulty: "medium",
    q: "In SpongeBob SquarePants, what is the name of Squidward's favorite instrument?",
    choices: ["Trumpet", "Saxophone", "Clarinet", "Flute"],
    answer: 2,
  },
  {
    theme: "Millennial Nostalgia",
    category: "TV",
    difficulty: "easy",
    q: "What MTV show featured Johnny Knoxville and a crew doing dangerous stunts?",
    choices: ["Punk'd", "Viva La Bam", "Jackass", "Wildboyz"],
    answer: 2,
  },
  {
    theme: "Millennial Nostalgia",
    category: "TV",
    difficulty: "medium",
    q: "In Lizzie McGuire, what was the name of Lizzie's animated alter ego?",
    choices: ["Cartoon Lizzie", "Mini Lizzie", "Pixel Lizzie", "Doodle Lizzie"],
    answer: 0,
    fact: "Fans just called it 'Animated Lizzie' / 'Cartoon Lizzie'.",
  },
  {
    theme: "Millennial Nostalgia",
    category: "TV",
    difficulty: "easy",
    q: "Which show asked the question \"How you doin'?\" via the character Joey Tribbiani?",
    choices: ["Seinfeld", "Friends", "Frasier", "Will & Grace"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "TV",
    difficulty: "medium",
    q: "On Drake & Josh, what is the catchphrase Josh yells at Drake?",
    choices: ["\"Drake!\"", "\"Megan!\"", "\"Hug me, brotha!\"", "\"Oh, come on!\""],
    answer: 0,
  },

  // ---------- MUSIC ----------
  {
    theme: "Millennial Nostalgia",
    category: "Music",
    difficulty: "easy",
    q: "\"Oops!... I Did It Again\" was a 2000 hit by which artist?",
    choices: ["Christina Aguilera", "Britney Spears", "Jessica Simpson", "Mandy Moore"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Music",
    difficulty: "easy",
    q: "Which boy band sang \"I Want It That Way\"?",
    choices: ["*NSYNC", "98 Degrees", "Backstreet Boys", "Boyz II Men"],
    answer: 2,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Music",
    difficulty: "medium",
    q: "\"Mr. Brightside\" is a 2004 staple by which band?",
    choices: ["The Killers", "The Strokes", "Franz Ferdinand", "Kings of Leon"],
    answer: 0,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Music",
    difficulty: "easy",
    q: "Complete the Outkast lyric: \"Shake it like a ___.\"",
    choices: ["Salt shaker", "Tail feather", "Polaroid picture", "Bottle of pop"],
    answer: 2,
    fact: "From \"Hey Ya!\" (2003).",
  },
  {
    theme: "Millennial Nostalgia",
    category: "Music",
    difficulty: "medium",
    q: "Soulja Boy told everyone to do which dance in 2007?",
    choices: ["The Dougie", "Crank That", "The Stanky Leg", "Cat Daddy"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Music",
    difficulty: "medium",
    q: "Which artist released the album \"The Marshall Mathers LP\" in 2000?",
    choices: ["Jay-Z", "Nelly", "Eminem", "50 Cent"],
    answer: 2,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Music",
    difficulty: "easy",
    q: "\"All Star\" by Smash Mouth became iconic largely because of which 2001 movie?",
    choices: ["Shrek", "Monsters, Inc.", "Mystery Men", "Rat Race"],
    answer: 0,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Music",
    difficulty: "easy",
    q: "Avril Lavigne asked why someone had to go and make things so complicated in which 2002 song?",
    choices: ["Sk8er Boi", "Complicated", "I'm with You", "My Happy Ending"],
    answer: 1,
  },

  // ---------- MOVIES ----------
  {
    theme: "Millennial Nostalgia",
    category: "Movies",
    difficulty: "easy",
    q: "In Mean Girls, on what day of the week do the Plastics wear pink?",
    choices: ["Mondays", "Wednesdays", "Fridays", "Sundays"],
    answer: 1,
    fact: "\"On Wednesdays we wear pink.\"",
  },
  {
    theme: "Millennial Nostalgia",
    category: "Movies",
    difficulty: "medium",
    q: "\"You had me at hello\" is a famous line from which 1996 film?",
    choices: ["Jerry Maguire", "As Good as It Gets", "You've Got Mail", "Notting Hill"],
    answer: 0,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Movies",
    difficulty: "easy",
    q: "In The Matrix, which colored pill does Neo take?",
    choices: ["Blue", "Green", "Red", "Yellow"],
    answer: 2,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Movies",
    difficulty: "medium",
    q: "What is the name of the kingdom in Shrek ruled by Lord Farquaad?",
    choices: ["Far Far Away", "Duloc", "Camelot", "Worcestershire"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Movies",
    difficulty: "medium",
    q: "In Napoleon Dynamite, what skill does Napoleon say girls want a guy to have?",
    choices: ["Nunchuck skills", "Computer hacking skills", "Bow staff skills", "All of the above"],
    answer: 3,
    fact: "\"...you know, like nunchuck skills, bow hunting skills, computer hacking skills...\"",
  },
  {
    theme: "Millennial Nostalgia",
    category: "Movies",
    difficulty: "easy",
    q: "Which 2004 movie features the news team anchor Ron Burgundy?",
    choices: ["Talladega Nights", "Anchorman", "Step Brothers", "Old School"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Movies",
    difficulty: "medium",
    q: "In Finding Nemo, what kind of fish is Dory?",
    choices: ["Clownfish", "Blue tang", "Angelfish", "Pufferfish"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Movies",
    difficulty: "easy",
    q: "\"My precious\" is the obsession of which Lord of the Rings character?",
    choices: ["Frodo", "Sauron", "Gollum", "Bilbo"],
    answer: 2,
  },

  // ---------- INTERNET / TECH ----------
  {
    theme: "Millennial Nostalgia",
    category: "Internet",
    difficulty: "hard",
    q: "What was the name of the dancing baby that became one of the first viral memes (late '90s)?",
    choices: ["Baby Cha-Cha", "Dancing Hamster", "Peanut", "Boogie Baby"],
    answer: 0,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Internet",
    difficulty: "medium",
    q: "On MySpace, the person in your top friends list was placed in your...",
    choices: ["Top 8", "Inner Circle", "Friend Zone", "Crew"],
    answer: 0,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Internet",
    difficulty: "easy",
    q: "What sound did AOL famously make when a message arrived?",
    choices: ["\"Ding!\"", "\"You've Got Mail!\"", "\"New message!\"", "\"Hello!\""],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Internet",
    difficulty: "easy",
    q: "What does the texting abbreviation \"BRB\" stand for?",
    choices: ["Be Right Back", "Big Red Button", "Bring Real Bagels", "By Real Bad"],
    answer: 0,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Internet",
    difficulty: "easy",
    q: "Which device let you carry \"1,000 songs in your pocket\" per its 2001 ad?",
    choices: ["Zune", "iPod", "Walkman", "Discman"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Internet",
    difficulty: "medium",
    q: "On AIM, what did you set when you stepped away from the computer?",
    choices: ["A status emoji", "An away message", "A vacation note", "A do-not-disturb sign"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Internet",
    difficulty: "medium",
    q: "What was the keychain virtual pet that started the digital-pet craze in the late '90s?",
    choices: ["Furby", "Tamagotchi", "Giga Pet", "Digimon"],
    answer: 1,
    fact: "Tamagotchi launched the craze in 1996/97; Giga Pets followed.",
  },

  // ---------- VIDEO GAMES ----------
  {
    theme: "Millennial Nostalgia",
    category: "Games",
    difficulty: "easy",
    q: "What is the name of the green-hatted brother in the Super Mario series?",
    choices: ["Wario", "Luigi", "Toad", "Yoshi"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Games",
    difficulty: "medium",
    q: "In Pokémon Red/Blue, which Pokémon is #001 in the Pokédex?",
    choices: ["Pikachu", "Charmander", "Bulbasaur", "Squirtle"],
    answer: 2,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Games",
    difficulty: "medium",
    q: "Which cheat code gives you 50,000 simoleons in The Sims?",
    choices: ["motherlode", "kaching", "moneyplz", "simoleons"],
    answer: 0,
    fact: "'kaching' gave 1,000; 'motherlode' gave 50,000.",
  },
  {
    theme: "Millennial Nostalgia",
    category: "Games",
    difficulty: "medium",
    q: "Which handheld console was famous for its dual screens and stylus (2004)?",
    choices: ["Game Boy Advance", "Nintendo DS", "PSP", "Game Gear"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Games",
    difficulty: "easy",
    q: "In Halo, what is the name of the player's iconic green-armored protagonist?",
    choices: ["Master Chief", "Cortana", "The Arbiter", "Sergeant Johnson"],
    answer: 0,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Games",
    difficulty: "easy",
    q: "Guitar Hero players used a controller shaped like what?",
    choices: ["A drum", "A microphone", "A guitar", "A keyboard"],
    answer: 2,
  },

  // ---------- SNACKS / BRANDS / STUFF ----------
  {
    theme: "Millennial Nostalgia",
    category: "Brands",
    difficulty: "medium",
    q: "What shoe brand made the original light-up sneakers beloved by '90s kids?",
    choices: ["Heelys", "L.A. Gear", "Skechers", "Reebok Pump"],
    answer: 1,
    fact: "L.A. Gear light-up shoes were the originals; others followed.",
  },
  {
    theme: "Millennial Nostalgia",
    category: "Brands",
    difficulty: "medium",
    q: "Which toy was a clear plastic ring you stepped into and swung around one ankle?",
    choices: ["Skip-It", "Pogo Ball", "Moon Shoes", "Sock'em Boppers"],
    answer: 0,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Brands",
    difficulty: "easy",
    q: "Dunkaroos paired a cookie with what?",
    choices: ["Pudding", "Frosting/dip", "Peanut butter", "Marshmallow"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Brands",
    difficulty: "medium",
    q: "What was the name of the small rubber-band bracelets kids traded and wore by the dozen (~2010)?",
    choices: ["Slap bracelets", "Silly Bandz", "Friendship bracelets", "Jelly bracelets"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Brands",
    difficulty: "hard",
    q: "Which drink came in a small barrel-shaped bottle with a foil top you ripped off?",
    choices: ["Capri Sun", "Sunny D", "Hi-C", "Little Hug Fruit Barrels"],
    answer: 3,
  },

  // ---------- CATCHPHRASES / CULTURE ----------
  {
    theme: "Millennial Nostalgia",
    category: "Culture",
    difficulty: "medium",
    q: "Borat made which phrase a 2006 catchphrase?",
    choices: ["\"Very nice!\"", "\"That's hot.\"", "\"Bazinga!\"", "\"Yeah, baby!\""],
    answer: 0,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Culture",
    difficulty: "medium",
    q: "Paris Hilton's signature catchphrase was...",
    choices: ["\"Whatever.\"", "\"That's hot.\"", "\"As if!\"", "\"Loves it.\""],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Culture",
    difficulty: "medium",
    q: "\"Talk to the hand\" was a dismissive phrase popular in which decade?",
    choices: ["1980s", "1990s", "2010s", "2020s"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Culture",
    difficulty: "medium",
    q: "Which of these was a must-have student binder/organizer before smartphones?",
    choices: ["Trapper Keeper", "Lisa Frank", "Mead Five Star", "All of the above"],
    answer: 3,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Culture",
    difficulty: "medium",
    q: "What \"chain\" message format threatened bad luck unless you forwarded it to 10 friends?",
    choices: ["A chain email", "A poke", "A wall post", "A tweet"],
    answer: 0,
  },

  // ---------- more TV ----------
  {
    theme: "Millennial Nostalgia",
    category: "TV",
    difficulty: "easy",
    q: "Who lives in a pineapple under the sea?",
    choices: ["Patrick Star", "SpongeBob SquarePants", "Squidward", "Mr. Krabs"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "TV",
    difficulty: "medium",
    q: "The Powerpuff Girls were created by which scientist?",
    choices: ["Dr. Brainstorm", "Professor Utonium", "Dexter", "Professor Membrane"],
    answer: 1,
    fact: "Made of sugar, spice, everything nice — and a dash of Chemical X.",
  },
  {
    theme: "Millennial Nostalgia",
    category: "TV",
    difficulty: "hard",
    q: "Arnold's distinctive head on Hey Arnold! is most often compared to what?",
    choices: ["A football", "An egg", "A square", "A lightbulb"],
    answer: 0,
  },

  // ---------- more MUSIC ----------
  {
    theme: "Millennial Nostalgia",
    category: "Music",
    difficulty: "easy",
    q: "\"Bye Bye Bye\" was a 2000 hit by which boy band?",
    choices: ["Backstreet Boys", "*NSYNC", "98 Degrees", "O-Town"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Music",
    difficulty: "medium",
    q: "\"In Da Club\" was a 2003 breakout hit by which rapper?",
    choices: ["Ja Rule", "50 Cent", "Nelly", "Ludacris"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Music",
    difficulty: "medium",
    q: "Which pop-punk band released \"All the Small Things\" in 1999?",
    choices: ["Sum 41", "Blink-182", "Green Day", "Good Charlotte"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Music",
    difficulty: "hard",
    q: "What was Lady Gaga's 2008 debut single?",
    choices: ["Poker Face", "Just Dance", "Bad Romance", "Paparazzi"],
    answer: 1,
  },

  // ---------- more MOVIES ----------
  {
    theme: "Millennial Nostalgia",
    category: "Movies",
    difficulty: "easy",
    q: "In Toy Story, what is the name of the cowboy doll?",
    choices: ["Buzz", "Woody", "Rex", "Hamm"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Movies",
    difficulty: "easy",
    q: "In the Shrek movies, what kind of creature is Shrek?",
    choices: ["A troll", "An ogre", "A giant", "A goblin"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Movies",
    difficulty: "medium",
    q: "In Harry Potter, which platform do students use to board the Hogwarts Express?",
    choices: ["Platform 9¾", "Platform 7½", "Platform 11", "Platform 13"],
    answer: 0,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Movies",
    difficulty: "medium",
    q: "In Cast Away (2000), what does Tom Hanks's character name his volleyball companion?",
    choices: ["Wilson", "Spalding", "Buddy", "Coconut"],
    answer: 0,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Movies",
    difficulty: "hard",
    q: "What is the name of the high school the Plastics attend in Mean Girls?",
    choices: ["North Shore High", "Bayside High", "East Great Falls High", "Ridgemont High"],
    answer: 0,
  },

  // ---------- more INTERNET / TECH ----------
  {
    theme: "Millennial Nostalgia",
    category: "Internet",
    difficulty: "easy",
    q: "What does the abbreviation \"LOL\" stand for?",
    choices: ["Lots of Love", "Laugh Out Loud", "Land of Legends", "Look Out Loud"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Internet",
    difficulty: "medium",
    q: "Which video-sharing site did Google acquire in 2006?",
    choices: ["Vimeo", "YouTube", "Metacafe", "Dailymotion"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Internet",
    difficulty: "hard",
    q: "Which early search engine had a butler mascot named Jeeves?",
    choices: ["Ask Jeeves", "AltaVista", "Lycos", "Excite"],
    answer: 0,
  },

  // ---------- more VIDEO GAMES ----------
  {
    theme: "Millennial Nostalgia",
    category: "Games",
    difficulty: "easy",
    q: "Which blue hedgehog is Sega's mascot?",
    choices: ["Sonic", "Crash", "Spyro", "Knuckles"],
    answer: 0,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Games",
    difficulty: "medium",
    q: "Which block-building game was created by Markus \"Notch\" Persson and released in 2011?",
    choices: ["Terraria", "Minecraft", "Roblox", "Lego Worlds"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Games",
    difficulty: "medium",
    q: "In Mario Kart, which item homes in on whoever is in first place?",
    choices: ["Red shell", "Blue (spiny) shell", "Banana", "Super Star"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Games",
    difficulty: "hard",
    q: "Which two directional inputs begin the famous \"Konami Code\"?",
    choices: ["Up, Up", "Left, Right", "Down, Down", "B, A"],
    answer: 0,
    fact: "The full code: Up, Up, Down, Down, Left, Right, Left, Right, B, A.",
  },

  // ---------- more BRANDS / TOYS ----------
  {
    theme: "Millennial Nostalgia",
    category: "Brands",
    difficulty: "easy",
    q: "Crocs are a brand of what?",
    choices: ["Sunglasses", "Foam clogs", "Backpacks", "Watches"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Brands",
    difficulty: "medium",
    q: "Which collectible cardboard discs did kids slam in a '90s playground game?",
    choices: ["Pogs", "Marbles", "Jacks", "Dominoes"],
    answer: 0,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Brands",
    difficulty: "hard",
    q: "Beanie Babies were made by which company?",
    choices: ["Hasbro", "Ty", "Mattel", "Fisher-Price"],
    answer: 1,
  },

  // ---------- more CULTURE ----------
  {
    theme: "Millennial Nostalgia",
    category: "Culture",
    difficulty: "easy",
    q: "\"Got Milk?\" was a long-running ad campaign for what?",
    choices: ["Cereal", "Milk", "Cookies", "Yogurt"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Culture",
    difficulty: "hard",
    q: "On the early-2000s website \"Hot or ___,\" users rated strangers' photos. Fill in the blank.",
    choices: ["Cold", "Not", "Cool", "No"],
    answer: 1,
  },
  {
    theme: "Millennial Nostalgia",
    category: "Culture",
    difficulty: "hard",
    q: "The yellow rubber \"Livestrong\" wristband raised awareness for which cause?",
    choices: ["Cancer research", "Heart disease", "Autism", "Diabetes"],
    answer: 0,
  },

  // =====================================================================
  // ============================ THEME: MARVEL ==========================
  // =====================================================================

  // ---------- easy ----------
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "easy",
    q: "What is Tony Stark's superhero alter ego?",
    choices: ["War Machine", "Iron Man", "Iron Patriot", "Vision"],
    answer: 1,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "easy",
    q: "What rare metal is Captain America's shield primarily made of?",
    choices: ["Adamantium", "Vibranium", "Titanium", "Carbon steel"],
    answer: 1,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "easy",
    q: "What is the name of Thor's enchanted hammer?",
    choices: ["Stormbreaker", "Gungnir", "Mjolnir", "Hofund"],
    answer: 2,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "easy",
    q: "What is the green, rage-fueled alter ego of scientist Bruce Banner?",
    choices: ["The Thing", "The Hulk", "Abomination", "Drax"],
    answer: 1,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "easy",
    q: "What is the alter ego of the original Spider-Man?",
    choices: ["Miles Morales", "Peter Parker", "Harry Osborn", "Eddie Brock"],
    answer: 1,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "easy",
    q: "Black Panther is the protector of which fictional African nation?",
    choices: ["Genosha", "Wakanda", "Sokovia", "Latveria"],
    answer: 1,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "easy",
    q: "Which super-team includes Iron Man, Captain America, Thor, and the Hulk?",
    choices: ["The X-Men", "The Avengers", "Guardians of the Galaxy", "Fantastic Four"],
    answer: 1,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "easy",
    q: "Natasha Romanoff is better known by what code name?",
    choices: ["Scarlet Witch", "Black Widow", "Gamora", "Captain Marvel"],
    answer: 1,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "easy",
    q: "The Hulk is most famously depicted as what color?",
    choices: ["Red", "Blue", "Green", "Grey"],
    answer: 2,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "easy",
    q: "Which purple villain seeks all six Infinity Stones in the MCU?",
    choices: ["Loki", "Ultron", "Thanos", "Kang"],
    answer: 2,
  },

  // ---------- medium ----------
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "medium",
    q: "What is the name of Thor's adoptive brother, the god of mischief?",
    choices: ["Heimdall", "Loki", "Baldur", "Fandral"],
    answer: 1,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "medium",
    q: "What is the name of Tony Stark's original AI assistant?",
    choices: ["FRIDAY", "J.A.R.V.I.S.", "E.D.I.T.H.", "KAREN"],
    answer: 1,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "medium",
    q: "Which Infinity Stone is housed inside the Tesseract?",
    choices: ["Mind Stone", "Space Stone", "Reality Stone", "Power Stone"],
    answer: 1,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "medium",
    q: "What is the real name of the Winter Soldier?",
    choices: ["Sam Wilson", "Bucky Barnes", "Clint Barton", "Brock Rumlow"],
    answer: 1,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "medium",
    q: "What is the real name of Star-Lord, leader of the Guardians of the Galaxy?",
    choices: ["Peter Quill", "Rocket", "Drax", "Yondu"],
    answer: 0,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "medium",
    q: "T'Challa's tech-genius younger sister is named what?",
    choices: ["Nakia", "Okoye", "Shuri", "Ramonda"],
    answer: 2,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "medium",
    q: "What is the real name of the Scarlet Witch?",
    choices: ["Wanda Maximoff", "Carol Danvers", "Jean Grey", "Jennifer Walters"],
    answer: 0,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "medium",
    q: "What new weapon does Thor obtain in Avengers: Infinity War?",
    choices: ["Mjolnir", "Stormbreaker", "Jarnbjorn", "Gungnir"],
    answer: 1,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "medium",
    q: "Which Infinity Stone was used to create the android Vision?",
    choices: ["Soul Stone", "Mind Stone", "Reality Stone", "Time Stone"],
    answer: 1,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "medium",
    q: "What is the real name of the MCU's Captain Marvel?",
    choices: ["Carol Danvers", "Monica Rambeau", "Maria Hill", "Sharon Carter"],
    answer: 0,
  },

  // ---------- hard ----------
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "hard",
    q: "In the comics, the herald of Galactus once known as Norrin Radd is called what?",
    choices: ["Silver Surfer", "Nova", "Terrax", "Firelord"],
    answer: 0,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "hard",
    q: "What is Wolverine's birth name in the comics?",
    choices: ["Victor Creed", "James Howlett", "Scott Summers", "Warren Worthington"],
    answer: 1,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "hard",
    q: "Which Marvel villain rules the fictional nation of Latveria?",
    choices: ["Magneto", "Doctor Doom", "Red Skull", "Kang"],
    answer: 1,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "hard",
    q: "In the MCU, Star-Lord's father turns out to be which Celestial being?",
    choices: ["Ego", "Kronos", "Mar-Vell", "Eson"],
    answer: 0,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "hard",
    q: "In the comics, which villain is responsible for the death of Gwen Stacy?",
    choices: ["Doctor Octopus", "Green Goblin", "Venom", "Vulture"],
    answer: 1,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "hard",
    q: "The cosmic Phoenix Force is most associated with which X-Man?",
    choices: ["Storm", "Rogue", "Jean Grey", "Emma Frost"],
    answer: 2,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "hard",
    q: "What is the day-job profession of Daredevil's alter ego, Matt Murdock?",
    choices: ["Journalist", "Lawyer", "Doctor", "Detective"],
    answer: 1,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "hard",
    q: "Which alien empire is the longtime enemy of the shape-shifting Skrulls?",
    choices: ["The Kree", "The Chitauri", "The Celestials", "The Brood"],
    answer: 0,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "hard",
    q: "Who is the original Ant-Man and a founding member of the Avengers in the comics?",
    choices: ["Scott Lang", "Hank Pym", "Bill Foster", "Eric O'Grady"],
    answer: 1,
  },
  {
    theme: "Marvel",
    category: "Marvel",
    difficulty: "hard",
    q: "In Norse-inspired Marvel lore, what is the name of the rainbow bridge guarded by Heimdall?",
    choices: ["Yggdrasil", "The Bifrost", "Valhalla", "Asbru"],
    answer: 1,
  },

  // =====================================================================
  // ============================ THEME: NATURE ==========================
  // =====================================================================

  // ---------- easy ----------
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "easy",
    q: "What is the largest land animal alive today?",
    choices: ["White rhinoceros", "African elephant", "Hippopotamus", "Giraffe"],
    answer: 1,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "easy",
    q: "Which gas do plants absorb from the air to perform photosynthesis?",
    choices: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"],
    answer: 2,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "easy",
    q: "What is the fastest land animal?",
    choices: ["Lion", "Cheetah", "Pronghorn", "Greyhound"],
    answer: 1,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "easy",
    q: "What sweet substance do bees produce?",
    choices: ["Wax", "Honey", "Syrup", "Pollen"],
    answer: 1,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "easy",
    q: "What do you call an animal that eats only plants?",
    choices: ["Carnivore", "Herbivore", "Omnivore", "Insectivore"],
    answer: 1,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "easy",
    q: "What is the largest animal known to have ever existed?",
    choices: ["Blue whale", "African elephant", "Argentinosaurus", "Sperm whale"],
    answer: 0,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "easy",
    q: "Which flightless bird lives in Antarctica and is an excellent swimmer?",
    choices: ["Ostrich", "Penguin", "Emu", "Kiwi"],
    answer: 1,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "easy",
    q: "What is a baby frog called?",
    choices: ["Tadpole", "Caterpillar", "Fry", "Nymph"],
    answer: 0,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "easy",
    q: "Which part of a plant typically carries out most photosynthesis?",
    choices: ["Roots", "Stem", "Leaves", "Flowers"],
    answer: 2,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "easy",
    q: "What is the tallest tree species on Earth?",
    choices: ["Giant sequoia", "Coast redwood", "Douglas fir", "Eucalyptus"],
    answer: 1,
    fact: "The coast redwood holds the height record; the giant sequoia is the largest by volume.",
  },

  // ---------- medium ----------
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "medium",
    q: "What is the largest organ of the human body?",
    choices: ["Liver", "Skin", "Lungs", "Brain"],
    answer: 1,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "medium",
    q: "How many legs does a spider have?",
    choices: ["Six", "Eight", "Ten", "Twelve"],
    answer: 1,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "medium",
    q: "What is the process by which a caterpillar transforms into a butterfly?",
    choices: ["Mitosis", "Metamorphosis", "Photosynthesis", "Hibernation"],
    answer: 1,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "medium",
    q: "Which is the largest ocean on Earth?",
    choices: ["Atlantic", "Indian", "Pacific", "Arctic"],
    answer: 2,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "medium",
    q: "What is the hardest known naturally occurring material?",
    choices: ["Quartz", "Diamond", "Titanium", "Granite"],
    answer: 1,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "medium",
    q: "Which egg-laying mammal has a duck-like bill?",
    choices: ["Platypus", "Kangaroo", "Sloth", "Armadillo"],
    answer: 0,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "medium",
    q: "A Komodo dragon is what type of animal?",
    choices: ["Amphibian", "Lizard", "Snake", "Crocodile"],
    answer: 1,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "medium",
    q: "Coral reefs are built by colonies of which tiny animals?",
    choices: ["Plankton", "Coral polyps", "Sponges", "Sea anemones"],
    answer: 1,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "medium",
    q: "What is the term for animals that are active at night?",
    choices: ["Diurnal", "Nocturnal", "Crepuscular", "Dormant"],
    answer: 1,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "medium",
    q: "Which gas makes up the largest portion of Earth's atmosphere?",
    choices: ["Oxygen", "Nitrogen", "Carbon dioxide", "Argon"],
    answer: 1,
    fact: "Nitrogen makes up roughly 78% of the atmosphere.",
  },

  // ---------- hard ----------
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "hard",
    q: "What is the only mammal capable of true, sustained flight?",
    choices: ["Flying squirrel", "Bat", "Colugo", "Sugar glider"],
    answer: 1,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "hard",
    q: "What is the scientific (binomial) name for modern humans?",
    choices: ["Homo erectus", "Homo sapiens", "Homo habilis", "Australopithecus"],
    answer: 1,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "hard",
    q: "Which biome is defined by frozen subsoil (permafrost) and very low temperatures?",
    choices: ["Taiga", "Tundra", "Savanna", "Steppe"],
    answer: 1,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "hard",
    q: "Which green pigment allows plants to absorb light for photosynthesis?",
    choices: ["Carotene", "Chlorophyll", "Melanin", "Xanthophyll"],
    answer: 1,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "hard",
    q: "What is the largest species of fish in the world?",
    choices: ["Great white shark", "Whale shark", "Tiger shark", "Basking shark"],
    answer: 1,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "hard",
    q: "Approximately what fraction of Earth's surface is covered by water?",
    choices: ["About 51%", "About 61%", "About 71%", "About 81%"],
    answer: 2,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "hard",
    q: "Which cell structure is known as the 'powerhouse of the cell'?",
    choices: ["Nucleus", "Ribosome", "Mitochondria", "Golgi apparatus"],
    answer: 2,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "hard",
    q: "Which animal has the longest known lifespan of any vertebrate?",
    choices: ["Galápagos tortoise", "Greenland shark", "Bowhead whale", "Koi fish"],
    answer: 1,
    fact: "Greenland sharks can live several centuries.",
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "hard",
    q: "What is the collective term for a group of lions?",
    choices: ["A pack", "A pride", "A herd", "A troop"],
    answer: 1,
  },
  {
    theme: "Nature",
    category: "Nature",
    difficulty: "hard",
    q: "The majority of the Amazon rainforest lies within which country?",
    choices: ["Peru", "Colombia", "Brazil", "Venezuela"],
    answer: 2,
  },

  // =====================================================================
  // ============================== THEME: USA ===========================
  // =====================================================================

  // ---------- easy ----------
  {
    theme: "USA",
    category: "USA",
    difficulty: "easy",
    q: "What is the capital of the United States?",
    choices: ["New York City", "Washington, D.C.", "Los Angeles", "Chicago"],
    answer: 1,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "easy",
    q: "How many states make up the United States?",
    choices: ["48", "50", "52", "13"],
    answer: 1,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "easy",
    q: "Who was the first President of the United States?",
    choices: ["Thomas Jefferson", "George Washington", "John Adams", "Abraham Lincoln"],
    answer: 1,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "easy",
    q: "On what date is U.S. Independence Day celebrated?",
    choices: ["July 4", "June 14", "September 17", "November 11"],
    answer: 0,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "easy",
    q: "Which ocean borders the East Coast of the United States?",
    choices: ["Pacific", "Atlantic", "Indian", "Arctic"],
    answer: 1,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "easy",
    q: "What are the three colors of the U.S. flag?",
    choices: ["Red, white, and blue", "Red, gold, and green", "Blue, white, and black", "Red, white, and green"],
    answer: 0,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "easy",
    q: "Which U.S. state is nicknamed the 'Sunshine State'?",
    choices: ["California", "Florida", "Arizona", "Hawaii"],
    answer: 1,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "easy",
    q: "In which city does the Statue of Liberty stand?",
    choices: ["Boston", "New York City", "Philadelphia", "Washington, D.C."],
    answer: 1,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "easy",
    q: "What is the national bird of the United States?",
    choices: ["Bald eagle", "Wild turkey", "American robin", "Red-tailed hawk"],
    answer: 0,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "easy",
    q: "Which U.S. founding document begins with the words 'We the People'?",
    choices: ["Declaration of Independence", "The Constitution", "Bill of Rights", "Gettysburg Address"],
    answer: 1,
  },

  // ---------- medium ----------
  {
    theme: "USA",
    category: "USA",
    difficulty: "medium",
    q: "Which U.S. state is the largest by land area?",
    choices: ["Texas", "California", "Alaska", "Montana"],
    answer: 2,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "medium",
    q: "Who was the primary author of the Declaration of Independence?",
    choices: ["Benjamin Franklin", "Thomas Jefferson", "John Adams", "George Washington"],
    answer: 1,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "medium",
    q: "Which issue was the central cause of the American Civil War?",
    choices: ["Taxation", "Slavery", "Religion", "Border disputes with Mexico"],
    answer: 1,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "medium",
    q: "How many stripes are on the U.S. flag?",
    choices: ["13", "50", "7", "12"],
    answer: 0,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "medium",
    q: "Which president appears on the U.S. one-dollar bill?",
    choices: ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "Benjamin Franklin"],
    answer: 1,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "medium",
    q: "In which city is the Liberty Bell located?",
    choices: ["Boston", "Philadelphia", "Washington, D.C.", "New York City"],
    answer: 1,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "medium",
    q: "The Great Lakes form part of the U.S. border with which country?",
    choices: ["Mexico", "Canada", "Russia", "Greenland"],
    answer: 1,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "medium",
    q: "Which president issued the Emancipation Proclamation?",
    choices: ["Ulysses S. Grant", "Abraham Lincoln", "Andrew Johnson", "Andrew Jackson"],
    answer: 1,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "medium",
    q: "Which U.S. state is the most populous?",
    choices: ["Texas", "California", "New York", "Florida"],
    answer: 1,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "medium",
    q: "Which mountain range stretches across the western United States and includes Colorado's highest peaks?",
    choices: ["Appalachian Mountains", "Rocky Mountains", "Sierra Nevada", "Cascade Range"],
    answer: 1,
  },

  // ---------- hard ----------
  {
    theme: "USA",
    category: "USA",
    difficulty: "hard",
    q: "How many U.S. presidents are carved into Mount Rushmore?",
    choices: ["Three", "Four", "Five", "Six"],
    answer: 1,
    fact: "Washington, Jefferson, Theodore Roosevelt, and Lincoln.",
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "hard",
    q: "Which was the 50th and most recent state to join the United States?",
    choices: ["Alaska", "Hawaii", "Arizona", "New Mexico"],
    answer: 1,
    fact: "Hawaii joined in August 1959, months after Alaska.",
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "hard",
    q: "The 1803 Louisiana Purchase acquired territory from which country?",
    choices: ["Spain", "France", "Britain", "Mexico"],
    answer: 1,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "hard",
    q: "Which amendment to the U.S. Constitution abolished slavery?",
    choices: ["13th", "14th", "15th", "19th"],
    answer: 0,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "hard",
    q: "Which president led the U.S. through most of the Great Depression and World War II, winning four elections?",
    choices: ["Harry Truman", "Franklin D. Roosevelt", "Herbert Hoover", "Dwight Eisenhower"],
    answer: 1,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "hard",
    q: "What is the capital city of the state of New York?",
    choices: ["New York City", "Albany", "Buffalo", "Rochester"],
    answer: 1,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "hard",
    q: "During which conflict did Abraham Lincoln deliver the Gettysburg Address?",
    choices: ["Revolutionary War", "War of 1812", "Civil War", "World War I"],
    answer: 2,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "hard",
    q: "How many original colonies declared independence from Britain in 1776?",
    choices: ["12", "13", "14", "15"],
    answer: 1,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "hard",
    q: "Which is the smallest U.S. state by area?",
    choices: ["Delaware", "Rhode Island", "Connecticut", "Hawaii"],
    answer: 1,
  },
  {
    theme: "USA",
    category: "USA",
    difficulty: "hard",
    q: "Which amendment to the Constitution protects freedom of speech?",
    choices: ["First Amendment", "Second Amendment", "Fourth Amendment", "Fifth Amendment"],
    answer: 0,
  },

  // =====================================================================
  // ============================= THEME: TRAVEL =========================
  // =====================================================================

  // ---------- easy ----------
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "easy",
    q: "In which city is the Eiffel Tower located?",
    choices: ["London", "Paris", "Rome", "Berlin"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "easy",
    q: "The Great Wall is a famous landmark of which country?",
    choices: ["Japan", "China", "India", "Mongolia"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "easy",
    q: "The Colosseum is a famous ancient landmark in which city?",
    choices: ["Athens", "Rome", "Madrid", "Istanbul"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "easy",
    q: "The Pyramids of Giza are located in which country?",
    choices: ["Mexico", "Egypt", "Greece", "Iraq"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "easy",
    q: "The Statue of Liberty was a gift to the United States from which country?",
    choices: ["Britain", "France", "Spain", "Italy"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "easy",
    q: "Mount Fuji is a famous mountain in which country?",
    choices: ["China", "South Korea", "Japan", "Nepal"],
    answer: 2,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "easy",
    q: "The Sahara Desert covers much of which continent?",
    choices: ["Asia", "Africa", "South America", "Australia"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "easy",
    q: "The clock tower commonly called 'Big Ben' is a landmark of which city?",
    choices: ["Dublin", "London", "Edinburgh", "Manchester"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "easy",
    q: "Which animal, a national symbol, is native to Australia?",
    choices: ["Llama", "Kangaroo", "Panda", "Reindeer"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "easy",
    q: "Which city is often called the 'City of Love'?",
    choices: ["Venice", "Paris", "Vienna", "Prague"],
    answer: 1,
  },

  // ---------- medium ----------
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "medium",
    q: "What is the capital of Japan?",
    choices: ["Kyoto", "Osaka", "Tokyo", "Sapporo"],
    answer: 2,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "medium",
    q: "The Taj Mahal is located in which country?",
    choices: ["Pakistan", "India", "Bangladesh", "Nepal"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "medium",
    q: "What is the capital of Australia?",
    choices: ["Sydney", "Melbourne", "Canberra", "Perth"],
    answer: 2,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "medium",
    q: "The ancient Inca site of Machu Picchu is located in which country?",
    choices: ["Mexico", "Peru", "Bolivia", "Chile"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "medium",
    q: "The Leaning Tower is found in which Italian city?",
    choices: ["Florence", "Pisa", "Milan", "Naples"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "medium",
    q: "Which river flows through the Egyptian capital, Cairo?",
    choices: ["The Amazon", "The Nile", "The Tigris", "The Congo"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "medium",
    q: "What is the capital of Canada?",
    choices: ["Toronto", "Vancouver", "Ottawa", "Montreal"],
    answer: 2,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "medium",
    q: "The Acropolis and the Parthenon are landmarks of which city?",
    choices: ["Rome", "Athens", "Cairo", "Istanbul"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "medium",
    q: "The city of Marrakech is located in which country?",
    choices: ["Egypt", "Morocco", "Tunisia", "Turkey"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "medium",
    q: "Which country contains more lakes than any other in the world?",
    choices: ["Russia", "Canada", "United States", "Finland"],
    answer: 1,
  },

  // ---------- hard ----------
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "hard",
    q: "What is the capital of Brazil?",
    choices: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"],
    answer: 2,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "hard",
    q: "Mount Kilimanjaro, Africa's highest peak, is located in which country?",
    choices: ["Kenya", "Tanzania", "Uganda", "Ethiopia"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "hard",
    q: "What is the smallest country in the world by area?",
    choices: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "hard",
    q: "The ancient rock-carved city of Petra is located in which country?",
    choices: ["Egypt", "Jordan", "Syria", "Lebanon"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "hard",
    q: "What is the capital of New Zealand?",
    choices: ["Auckland", "Wellington", "Christchurch", "Hamilton"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "hard",
    q: "Which strait separates Spain from Morocco at the western mouth of the Mediterranean?",
    choices: ["Bosphorus", "Strait of Gibraltar", "Strait of Hormuz", "Dardanelles"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "hard",
    q: "Angkor Wat, the world's largest religious monument, is located in which country?",
    choices: ["Thailand", "Cambodia", "Vietnam", "Laos"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "hard",
    q: "Which African country was historically known as Abyssinia?",
    choices: ["Eritrea", "Ethiopia", "Somalia", "Sudan"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "hard",
    q: "What is the capital of South Korea?",
    choices: ["Busan", "Seoul", "Incheon", "Daegu"],
    answer: 1,
  },
  {
    theme: "Travel",
    category: "Travel",
    difficulty: "hard",
    q: "Which is the largest hot desert in the world?",
    choices: ["Gobi", "Sahara", "Kalahari", "Arabian"],
    answer: 1,
  },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { QUESTIONS };
}
